//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLoginApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Folder
    {
        public Folder()
        {
            this.File = new HashSet<File>();
            this.Folder1 = new HashSet<Folder>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual ICollection<File> File { get; set; }
        public virtual ICollection<Folder> Folder1 { get; set; }
        public virtual Folder Folder2 { get; set; }
        public virtual UserList UserList { get; set; }
    }
}
