//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLoginApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shared
    {
        public int SharerID { get; set; }
        public int SharedID { get; set; }
        public string SharedFilePath { get; set; }
        public string SharedFolderPath { get; set; }
        public int ID { get; set; }
    
        public virtual UserList UserList { get; set; }
        public virtual UserList UserList1 { get; set; }
    }
}
