//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLoginApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserList
    {
        public UserList()
        {
            this.File = new HashSet<File>();
            this.Folder = new HashSet<Folder>();
            this.Shared = new HashSet<Shared>();
            this.Shared1 = new HashSet<Shared>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public string Mail { get; set; }
        public bool ConfirmationStatus { get; set; }
        public string ConfirmationToken { get; set; }
    
        public virtual ICollection<File> File { get; set; }
        public virtual ICollection<Folder> Folder { get; set; }
        public virtual ICollection<Shared> Shared { get; set; }
        public virtual ICollection<Shared> Shared1 { get; set; }
    }
}
